udistrital/cumplidos_dve_cliente

README.md, src/app/pages/carga-documentos-docente/carga-documentos-docente.component.html, src/app/pages/carga-documentos-docente/carga-documentos-docente.component.spec.ts, src/app/pages/carga-documentos-docente/carga-documentos-docente.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/styles.scss
feat: Se agrega el módulo de carga-documentos-docente, se adjunta la ruta del componente, se corrigen nombre en el archivo readme y se cambia la paleta de colores en el archivo styles.scss
=> feat: Se agrega el modulo de carga-documentos-docente

src/app/@core/models/respuesta.ts, src/app/@core/models/tabla_carga_documentos_docente.ts, src/app/app.module.ts, src/app/pages/carga-documentos-docente/carga-documentos-docente.component.html, src/app/pages/carga-documentos-docente/carga-documentos-docente.component.scss, src/app/pages/carga-documentos-docente/carga-documentos-docente.component.spec.ts, src/app/pages/carga-documentos-docente/carga-documentos-docente.component.ts, src/app/pages/pages.module.ts, src/app/pages/services/utilService.ts, src/environments/environment.test.ts, src/environments/environment.ts
feat: Se desarrolla la vista y la logica de solicitud_cumplidos_docente, y se agrega el botón de crear solicitud, se hace uso del endpoint del cumplidos_dve_mid
=> feat: Se desarrolla la vista y la logica de solicitud_cumplidos_docente

src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.html, src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts, src/app/pages/pages.module.ts, src/app/pages/services/ver-soportes.service.spec.ts, src/app/pages/services/ver-soportes.service.ts, src/app/pages/ver-soportes/ver-soportes.component.html, src/app/pages/ver-soportes/ver-soportes.component.scss, src/app/pages/ver-soportes/ver-soportes.component.spec.ts, src/app/pages/ver-soportes/ver-soportes.component.ts, src/environments/environment.test.ts, src/environments/environment.ts
feat: Se desarrolla el cuadro emergente, relacionado a ver-soportes, se agrega una nueva variable de entorno y se comienza con el desarrollo del cambio de estado, con respecto a las solicitudes.
=> feat: Se desarrolla el cuadro emergente, relacionado a ver-soportes

src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.html, src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts, src/app/pages/services/utilService.ts, src/styles.scss
feat: Se desarrolla la funcionalidad para el envío de los cumplidos, esta se debe de oculta cuando se habilita en varios estados del cumplido, ya sea cuando es RECHAZADA o CARGANDO DOCUMENTOS
=> feat: Se desarrolla la funcionalidad para el envío de los cumplidos

src/app/@core/models/tabla_cumplidos.ts, src/app/@core/models/tabla_peticiones.ts, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.html, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.scss, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.spec.ts, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/carga-documentos-docente/carga-documentos-docente.component.ts, src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/app/pages/services/utilService.ts, src/environments/environment.test.ts, src/environments/environment.ts
feat: Se crea el nuevo menú relacionado a aprobacion coordinador y todo lo que esta vista debe llevar como lo es la logica para traer las peticiones, aprobar y rechazar peticiones, tambien se hacen pequeñas correcciones con respecto a la visualizacion del estado de una solicitud
=> feat: Se crea el nuevo menú relacionado a aprobacion coordinador

src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts
feat: Se realiza el cambio con respecto en la lógica, ya que al momento de enviar el cumplido a revisión por parte del docente, el campo Responsable y CargoResponsable, deben de cambiar a los datos del coordinador.
=> feat: Se realiza el cambio con respecto en la logica de creacion cumplidos

src/app/@core/models/tabla_peticiones_supervisor.ts, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.html, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.scss, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.html, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.scss, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.spec.ts, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts, src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts, src/environments/environment.test.ts, src/environments/environment.ts
feat: Se desarrolla la sección de aprobación coordinador, y se realizan ciertas correcciones a con respecto a la aprobación de los cumplidos de coordinador, y unas pequeñas correcciones con respecto al código.
=> feat: Se desarrolla la sección de aprobación coordinador, y se realizan ciertas correcciones

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.scss, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.html, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.scss, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts
feat: Se desarrolla la funcionalidad asociada a la aprobación de peticiones, rechazo de peticiones y aprobación de múltiples peticiones por parte del supervisor, por otra parte, se realizan pequeñas correcciones al componente de aprobación coordinador.
=> feat: Se desarrolla la funcionalidad asociada al supervisor

src/app/@core/models/tabla_peticiones_ordenador.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.html, src/app/pages/aprobacion-pago/aprobacion-pago.component.scss, src/app/pages/aprobacion-pago/aprobacion-pago.component.spec.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts, src/app/pages/pages-routing.module.ts, src/app/pages/pages.module.ts
feat: Se desarrolla la vista asociada a aprobacion_pago
=> feat: Se desarrolla la vista asociada a aprobacion_pago

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.html, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts, src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts
feat: Se desarrolla la logica asociada a aprobacion pago, en conjunto con las acciones de aprobación y rechazo, y se hacen correcciones con respecto al tema de las fechas del por el refactor en el crud que se realizo
=> feat:Se desarrolla la logica asociada a aprobacion pago

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.html, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts
feat: Se realizan diversos ajustes tales como, la aparición del nombre del ordenador del gasto, asignar un documento de identidad de ordenador del gasto, al momento de aprobar la solicitud, entre otros
=> feat: Se realizan diversos ajustes tales como, la aparición del nombre

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts
feat: Se borra el dato de selección del siguiente año en el campo de año para la generación de Certificados en ambos roles.
=> feat: Se borra el dato de selección del siguiente año en el campo de año

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts, src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts, src/environments/environment.prod.ts
feat: Se desarrolla la funcionalidad asociada para el envío de cumplidos a TITAN y se envían los commit anteriores para realizar una actualización de los commit en la rama develop
=> feat: Se desarrolla la funcionalidad asociada para el envío de cumplidos a TITAN

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts, src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts, src/app/pages/dashboard/dashboard.component.html, src/app/pages/dashboard/dashboard.component.ts
feat: Se desarrolla la lógica asociada a la visualización de los diferentes manuales según el rol que se posee el usuario, por otra parte, se corrige el error de visualización que existia en las vista de coordinador, supervisor y ordenador del gasto, al momento de aprobar o rechazar una ultima petición y la vista no se actualizaba.
#111
=> feat: Se desarrolla la lógica asociada a la visualización de los diferentes manuales según el rol que se posee el usuario

src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts, src/environments/environment.test.ts, src/environments/environment.ts
- Se corrigen la logica para relacionada a las fechas en las cuales se pueden crear los cumplidos
=> fix: udistrital/cumplidos_dve_cliente#121 Fix_de_fechas

src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts
fix: Se pone en funcionamiento la sección que consulta al ordenador del gasto al aprobar por supervisor.
=> fix: Se pone en funcionamiento la sección que consulta al ordenador

src/environments/environment.prod.ts
fix: Corrección de variables de entorno para producción.
=> fix: Corrección de variables de entorno para producción.

src/app/pages/dashboard/dashboard.component.ts
fix: Se corrige error el cual no permitía listar los manuales asociados a cada rol del usuario.
=> fix: Se corrige error el cual no permitía listar los manuales asociados a cada rol del usuario.

src/environments/environment.prod.ts
fix: Se realiza la eliminación de comas, ya que genera ciertos errores al momento de generar los certificados.
=> fix: Se realiza la eliminación de comas

src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts
fix: Se cambia el mensaje de inicio cuando no se tiene registrada ninguna solicitud de cumplido para el contrato.
=> fix: Se cambia el mensaje de inicio cuando en creacion_cumplidos_docente

src/app/pages/aprobacion-pago/aprobacion-pago.component.ts, src/app/pages/creacion-cumplidos-docente/creacion-cumplidos-docente.component.ts
- Se ajusta el cliente para que se eliminen los paréntesis del nombre de los docentes en caso de existir, al momento de generar el certificado por parte de los decanos.
=> fix: Se ajusta el cliente para que se eliminen los parentesis del nombre de los docentes en caso de existir.

src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts, src/app/pages/dashboard/dashboard.component.html
Se abre pull request para actualizar rama develop y poder continuar con los desarrollos siguiendo los lineamientos propuestos
=> Se solicita actualizacion de la rama develop

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.html, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts
Se solicita revision para hacer el merge de la caracteristica de aprobacion multiple de cumplidos en el rol de coordinador en la rama develop, se adjuntan pantallazos de la prueba de funcionalidad en local.
1.)
2.)
3.)
=> Se termina feature de aprobacion multiple coordinador, paso a rama develop

src/app/pages/aprobacion-pago/aprobacion-pago.component.html, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts
#145 se termina de implementar funcionalidad de aprobacion multiple para ordenador del gasto
=> feat: se termina aprobacion ordenador

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts
correccion en tipado innecesario, validacion y comparaciones estrictas
=> fix: correcciones en sintaxis

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.html, src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.html, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts
#145 se termina funcionalidad de aprobacion multiple para todos los roles, solicitud de merge a rama release
=> feat: aprobacion multiple para todos los roles

src/app/pages/aprobacion-coordinador/aprobacion-coordinador.component.ts, src/app/pages/aprobacion-pago/aprobacion-pago.component.ts
Se incluye periodo academico intersemestral para la generacion de los certificados de coordinador y ordenador del gasto.
Tarea Iris #C-005802
=> fix: Generacion certificado de cumplimiento

src/polyfills.ts
Arreglo de bug Uncaught RangeError: Maximum call stack size exceeded
=> fix: Arreglo de bug Uncaught RangeError: Maximum call stack size exceeded
